version: '3.8'

services:
  sql-server:
    image: armikom-sql
    build:
      context: sql-server
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "KarmasikParol@1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - sql-network
 
networks:
  sql-network:

volumes:
  sql-data:
    driver: local